= Solution Patterns: Template Name
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

This solution pattern integrates a number of open source components that ingest and summarize
financial stock symbol data as it becomes available. It mimics how a human might need to analyse and summarize information from 
a variety of companies that trade on the NYSE and NASDAQ markets. It is intended to be used as a starting point for your own solution. 

*Contributors:* Bob Kozdemba and Josh Reagan. Red Hat, Inc.

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Common use cases that can be address with this architecture are:

- Financial Analysis
- Summarization of medical patient records
- General Retreival Augmented Generation workflows

include::01-pattern.adoc[]
